### ISSUE TITLE
Your download speed sucks.

### ISSUE THREAD

**Issue by techsideofficial** [n6617x/Fortnitebuilds#44]
![image](https://github.com/simplyblk/Fortnitebuilds/assets/68258126/2846d2b4-a8d5-48f7-8046-92531c1d2915)

**Comment by techsideofficial** [comment]
@Aeyth8 Why are the speeds really fast, and then go to like 6 hours remaining at 95%?

**Comment by Aeyth8** [comment]
Wouldn't have a clue, limited bandwidth?

**Comment by PizzaGod873** [comment]
Also it's not their fault, its your and github's.

**Comment by PizzaGod873** [comment]
My bad, not githubs, but the file hosting service

**Comment by n6617x** [comment]
This is a free archive with no donations. 🙂
